[package]
name = "lispust-http"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "http-server"
path = "src/server.rs"

[dependencies]
lispust-core = { path = "../lispust-core" }
actix-web = "3"
